apiVersion: apps/v1
kind: Deployment
metadata:
  name: task06-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task06-app
  template:
    metadata:
      labels:
        app: task06-app
    spec:
      containers:
        - name: task06
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: task06-secret
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task06-secret
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: task06
                  key: postgres_host
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: task06
                  key: postgres_db
          image: ibesedin/task06:1.0
          ports:
            - name: web
              containerPort: 8000